services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      PGDATA: /data/pgdata
    volumes:
      - data_db:/data/pgdata
    networks:
      - service
  api:
    container_name: service_api
    build: .
    ports:
      - "3434:8000"
    depends_on:
      - db
    networks:
      - service
    env_file:
      - ./.env
    environment:
      APP_PORT: 8000

networks:
  service:
    driver: bridge

volumes:
  data_db:
